---
title: "Confirmatory factor analysis (CFA) of multivariate lipid distributions across time and race-ethnic groups: United States, 2003-2012"
author: "Ann Von Holle, Kari E. North"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  word_document:
    toc: yes
  html_document:
    csl: ama.csl
    css: style.css
    depth: 3
    highlight: tango
    number_sections: yes
    theme: readable
    toc: yes
csl: ama.csl
bibliography: bib1.bib
---

<!-- 
NOTES:

1. This document will be downloaded in text format so any formatting such as bullet points, font changes, bolding, header choices will not be saved. However, please add comments or edits as you see fit. I can clean up later.
2. Any text below preceded by an @ symbol is a placeholder for a citation.
3. To indicate formatting in plain text use the following notation.
Sections in this document start with a # symbol. Section 1 headings start with #, section 2 headings start with ##, etc..
**bold**
*italic*
$latex formula$
4. If you want to see what the text below looks like after formatting, you can cut and paste in https://stackedit.io/editor OR you can go to the web page with a recent version of updates in Word doc format: draft
END OF NOTES
-->

# Abstract
 
Dyslipidemia, a well-established risk factor for cardiovascular disease (CVD), incorporates lipids and lipoproteins found in common profiles such as low density lipoprotein cholesterol (LDL-C), high density lipoprotein cholesterol (HDL-C) and triglycerides (TG). These measures are commonly evaluated across socio-demographic groups in a univariate format -- one at a time. Assessing dyslipidemia as a multivariate construct is possible, and perhaps also meaningful, in the context of confirmatory factor analysis (CFA), but no thorough assessment exists in the literature.

To assess a multivariate construct of dyslipidemia, we will use CFA to form a latent factor with three commonly assessed lipids and lipoproteins including LDL-C, HDL, TG as indicators. In turn, we will assess measurement invariance (MI) of the construct across demographic characteristics of age, race/ethnicity and sex in a United States representative sample of children ages 12 to 19 years.

Proper model fit will guide suitability of these indicators for a dyslipidemia construct in analyses. If measurement invariance across racial/ethnic or gender groups exists then there would also be no evidence of differences in the construct itself across these groups and allows for comparisons in means of the construct [@van_de_schoot_editorial:_2015]. Also, similarities across groups implies the measured lipid indicators have similar pair-wise correlations. Conversely, measurement variance is an indicator that this latent factor is not the same across groups and should be treated as such with stratification.

Results:

Measurement invariance (MI) did not hold in this sample. Tests for MI across racial/ethnic or gender groups are significant indicating that these groups have different multivariate shapes of the three lipid/lipoproteins and the means of these constructs cannot be compared across groups. Within strata of gender or race, the construct has good fit via fit statistics making it a valid construct.

Conclusion:

Analyses demonstrate this construct is an alternate way to evaluate dyslipidemia using structural equation models. However, evaluation of this construct across socio-demographic groups such as race/ethnicity and gender provides evidence of a different multivariate structure requiring stratification.

# Introduction

Dyslipidemia is often characterized through measures of triglycerides (TG), high-density lipoprotein cholesterol (HDL-C), and low-density cholesterol (LDL-C) from a common lipid panel. These measures are then analyzed in research on a univariate basis or with ratios. Another analytic approach can include confirmatory factor analysis (CFA). In practice, this approach would reduce the dimension of three indicators mentioned above to one latent variable capturing the pairwise correlation between measures. In turn, the resulting latent construct can be used either as an exposure or outcome in structural equation models. Although this sort of multivariate analysis can provide a different perspective compared to univariate and traditional approaches, it has not been investigated in the literature as a feasible analytic approach.

CFA is useful for a set of indicators that are interrelated and have already been established in a substantive theoretical sense independent of a statistical rationale. For the three indicators of interest in this particular study: HDL-C, LDL-C, and TG, there exists a strong rationale to treat them together to represent dyslipidemia [@bays_national_2016]. Although there are other indicators of dyslipidemia, these three are the most accessible in common lipid profiles and the most reported in the literature. Any changes in these values represented by a latent factor would be recognizable to lipid researchers and of value in research. What would most likely occur in the construct is a positive correlation between TG and LDL-C and a negative correlation between HDL-C and the prior two indicators. A one unit change in the latent factor in this case could represent an increase in TG and LDL-C alongside a decrease in HDL-C given the well established correlations between these measures.

A further motivation to examine dyslipidemia in a dimension reduction approach is its similarity to ratios when characterizing lipids. One could consider the correlations between the indicators to be an analog to ratios, with an additional ability to retain the variability for each lipid indicator. For example, the use of HDL to TG ratios is increasing in the literature, but analyses using a ratio has limitations [@kuh_correlation_1955; @atchley_ratios_1978; @kronmal_spurious_1993] including failure to adequately adjust for each of the variables forming the ratio when used as a covariate in a linear regression [@kronmal_spurious_1993].  Unlike a ratio, characterizing the variance of each lipid indicator is possible with a CFA latent construct.

Prior to implementation of this approach it is important to investigate if this latent construct represented in the CFA has a good model fit. Poor model fit would indicate that the fitted latent construct does not match the observed data very well and does not serve as a proper latent variable within a numerical dyslipidemia construct. For example, if the indicators are not correlated with one another then this approach is not feasible. Nor is it feasible if the choice of indicators does not fit within a sound theoretical basis. Neither of these cases apply to lipids used in common lipid profiles, and these two requirements make a case for examining dyslipidemia as a latent factor in CFA with the intent of using it in the future either as an exposure or outcome.

Assuming the three measures provide a good source of model fit, a next step would be to evaluate if the form of the latent construct of dyslipidemia stays relatively constant across demographic groups including race/ethnicity, age and gender. Similar form of the construct across different socio-demographic groups allows comparisons of construct means across these groups -- a basic outcome of interest. One common method used to assess this property is measurement invariance (MI) of the latent factor across demographic groups [@van_de_schoot_editorial:_2015-1]. Absent MI, comparing construct means across the demographic groups is more difficult to accomplish. An alternative approach in that resulting scenario would be to stratify analyses for make meaningful inference.

Although the CFA requires additional knowledge of structural equation modeling, the ability to capture correlations between lipid and lipoprotein indicators, separately estimate measurement error, and condense the indicators into a single latent variable can provide a parsimonious alternative approach to characterize dyslipidemia. Our aim in this study is to assess the fit and test measurement invariance of a latent construct representing dyslipidemia in a U.S.-representative sample. In turn, this assessment and tests can provide evidence of the viability of this construct in future models incorporating dyslipidemia.

# Methods

National Health and Nutrition Examination Survey (NHANES) is a nationwide representative complex survey sample in the United States that assesses population health. Lipid measures are among the data collected in the physical exam [@_nhanes_2017-3]. These analyses include NHANES samples from 2003-2012, spanning ten years. TC and TG were obtained via from venous samples with enzymatic methods [@_nhanes_2017-1; @carroll_trends_2012]. HDL were were measured with a direct immunoassay method [@_nhanes_2017], LDL-C was determined from the Friedewald equation. We included children ages 12 to 19 years in the sample and further subsetted the sample to include the largest racial/ethnic groups in the sample: non-Hispanic White, non-Hispanic Black, and Mexican American. Also, those reporting taking lipid lowering medication were excluded from the sample. After these exclusions there were xx individuals in the complex survey sample.

The primary aim is to create a latent construct of dyslipidemia. We conducted a CFA by specifying one latent variable, named dyslipidemia, with three indicators: LDL-C, HDL-C and TG. We specified three factor loadings, one for each indicator, and three error variances creating a ‘just identified’ model with zero degrees of freedom [@brown_confirmatory_2015]. All variables required for complex survey sampling were used in the analyses, including the sampling weights, strata and clustering information. We used the Comparative Fit Index (CFI), adjusted Bayesian Information Criterion (aBIC) and Root Mean Square Error of Approximation (RMSEA) to select the model with best fit.

Measurement invariance was determined by specifying 1) configural, 2) metric and 3) scalar models [@_mplus_2017; @van_de_schoot_checklist_2012]. Socioeconomic groups included age (12-13, 14-15, 16-17, 18-19 years), gender and racial/ethnic groups (Mexican American, non-Hispanic Black, non-Hispanic White, other Hispanic, and ‘Other’). The configural model allows the factor loadings and intercepts to vary across the groups; the metric model holds the factor loading the same across groups; the scalar model holds both the intercept and factor loadings to be the same across groups. To test differences between each of the models we used the chi-square test with a scaling correction factor. If significant, then there was evidence that the more complex model included significant terms that should remain in the model [@brown_confirmatory_2015]. If not significant then we kept the model with fewer parameters.

One aspect that was not possible to incorporate into the model was the method to subset complex survey data given the sampling weights. We did sensitivity tests to determine any bias in ignoring that assumption made on the model parameter estimation and did not detect any difference in effect, considered negligible in substantive meaning.

We used Mplus version 8 [@muthen_mplus_1998] for the CFA analysis and R [@r_core_team_r:_2017; @hallquist_mplusautomation:_2017] for other data handling tasks.

# Results

We determined model fit across groups by conducting Chi-Square invariance tests of three different models against each other in each of the three groupings: race/ethnicity, gender, and age. The best fitting model was the most parsimonious model that was no different, i.e. non-significant, from the more complex model.

When comparing gender, racial/ethnic, and age groups, the metric model, allowing intercepts to vary but fixed factor loadings, was not significantly different (Chi-Square=5.6, 2 df, p<0.06; Chi-Square=11.6, 8 df, p>0.16; Chi-Square=8.8, 4 df, p>0.06, respectively) from the configural model, which allowed both loading and intercepts to vary, indicating similarity of factor loadings. On the other hand, the scalar model, fixing both intercepts and factor loadings was different from the configural model (Chi-Square=71.1, 5 df, p<0.0001; Chi-Square=189.2, 20 df, p<0.0001; Chi-Square=86.5, 10 df, p<0.0001, respectively), indicating a difference in factor intercepts. Evidence for different factor intercepts is further supported by a significant test of the scalar versus metric model (Chi-Square=68.8, 3 df, p<0.0001; Chi-Square=198.8, 12 df, p<0.0001, Chi-Square=82.0, 6 df, p<0.0001, respectively). Thus the best fitting model across different gender, racial/ethnic, and age groups is one with similar factor loadings across the groups, but different factor intercepts -- the metric model.

Model fit information (Table 1) was satisfactory for the analyses by gender, racial/ethnic and age groups. First, RMSEA was below 0.05 in all three cases. Second, CFI was above 0.98. Third, aBIC was lowest for the metric model for all three models with the exception of the gender groups, and in this scenario, the difference between the configural and metric model was less than 4 points, considered to be a negligible difference. All of these measures of model fit point towards the metric model having satisfactory model fit and useful for further exploration of the model parameters [@brown_confirmatory_2015].

CFA intercepts are parameters of interest for the best fitting model because they vary across groups in the metric specification of the model. One can think of the intercept for each subgroup to be the mean lipid outcome for the average dyslipidemia factor -- in this case when the dyslipidemia factor is zero since it is mean-centered in these analyses. In table 2, the intercepts for the confirmatory factor representing dyslipidemia are described by groups within each separate model. 

Within the model that separates by age, the three older age groups appear to have lower intercepts for HDL, with a standardized intercept resting at -0.163 for the 14 to 16 and 17 to 19 year age groups. For the middle age group, ages 14 to 16, LDL and TG intercepts are shifted further to the negative direction. In contrast, the 17 to 19 year old group have LDL and TG intercepts that are shifted closer to the origin when compared to the youngest age group. Intercepts for gender groups demonstrate that males appear to have a shift of intercept in the negative direction for HDL and towards the origin for TG when compared to females. 

Finally, the racial/ethnic groups also have differences in their CFA intercepts. Using the Mexican American (MA) group as a referent, the non-Hispanic Blacks (NHB) have a positive intercept for HDL unlike the majority of the other groups and the largest negative shift in the intercept for TG compared to the other groups. The non-Hispanic White group appears to have similar intercept values compared to the MA group. Lastly, the other Hispanic (OH) group appears to have the largest  negative shift in LDL-C. These differences in intercepts for the groups have consequences for intergroup comparisons as will be discussed.

Factor loadings are not allowed to vary across groups in the metric model. Standardized factor loadings without cross-loadings -- as in the specified analyses -- indicate the correlation between the dyslipidemia factor and the indicator while omitting measurement error. The TG indicator has the strongest correlation with the factor, at a correlation exceeding 0.71. HDL has the second strongest association -- around -0.52. Finally, LDL is the least correlated with the factor with a correlation at 0.39 for this sample. Any standardized factor loading below 0.3 indicates need to remove that indicator, and none of the lipid indicators fit that description. These values culminate in an interpretation of a one unit increase in the factor equating with an increase in unfavorable levels of lipids: declining HDL and increasing TG and LDL.

# Discussion

The purpose of this paper was to examine the use of CFA as a measure of dyslipidemia. First, we evaluated measures of model fit of a CFA with three common lipid measures serving as observed indicators in the model: HDL-C, LDL-C and TG. Nested within this aim is the concept that this CFA dyslipidemia construct may not be similar across sociodemographic groups such as race/ethnicity, age and gender -- common ground for comparisons. Given known differences in the factor across these demographic categories, we tested this latter hypothesis through the measurement invariance (MI) concept. MI did not hold for different racial/ethnic, age or gender groups implying that the factor means can not be meaningfully compared across these groups without special treatment [@van_de_schoot_facing_2013], which has implications for future use.

## Measurement Invariance

In evaluating the three different types of models across subgroups for each of the following domains: age, race/ethnicity and sex of child, the metric model was the best of the three for all domains. The configural model, in which all factor loadings and means of the dyslipidemia factor were allowed to vary across groups, was not statistically significantly different from the metric model. Given this result, the metric model offers a parsimonious fit by fixing the factor loadings to be the same across groups. Furthermore, the metric model was different from the scalar model, adding more evidence to support the choice of the metric model.

Testing of measurement invariance may have intriguing implications. First, there is no evidence for differences in factor loadings across any subgroups of for race/ethnicity, gender and age. This finding supports the idea that the three lipid indicators covary similarly no matter the choice of sociodemographic subgroup. Confounding may play less of a part in this explanation than that for the adult population as exposure to smoking and lifestyle choices has had less time to exact a cumulative toll. Also, a similarity of factor loadings across subgroups may have relevance for lipid ratio measures such as HDL to TG, a commonly used metric. For example, a dyslipidemia factor with positive HDL-C factor loadings combined with negative LDL-C and TG factor loadings translates to a simultaneous increase of HDL and decrease in LDL-C and TG. In turn this factor interpretation could be an analog to HDL-C to TG ratio changes, implying  generalizability of these ratios across sociodemographic subgroups. No research has been done comparing these measures and would be of interest.

Although the factor loadings for the construct are similar, we did not find evidence that metric invariance holds for these subgroups. Metric non-invariance implies at least one group has a different response to the lipid latent construct [@van_de_schoot_checklist_2012]. For example, when the factor is equal to zero for all subgroups, the estimated mean indicator (HDL-C, LDL-C and TG), the intercept, is different depending on the subgroup you choose. These multivariate findings, especially of the African American group having lower TG and higher HDL is in line with prior findings of univariate mean differences across racial/ethnic groups [@sumner_ethnic_2009; @kit_prevalence_2015].

Importantly, metric non-invariance for this factor restricts the use of mean factor scores across subgroups. Using factor scores as observed entities followed by subgroup comparisons, given non-invariance, may result in scientifically meaningless estimates. Measurement non-invariance for all three domains supports different dyslipidemia constructs for each of the selected subgroups for race/ethnicity, age and gender. Although this finding remains restricted to this sample, it is of a nationwide representative sample of children in the United States and provides a cautionary tale of interpretation when conducting analyses in other samples.

## Fit

Finally, having chosen the metric model for all of the three domains, we determined that model fit diagnostics were within normal bounds of adequate to good fit and as such motivates further use of this construct. Use of this construct would be an interesting adjunct to univariate outcomes with a different and meaningful interpretation.

Strengths of these analyses include the representation of the 12 to 19 year old population in the United States. Also, measuring dyslipidemia as one joint distribution that incorporates the correlation between each of three commonly measured lipids is worthwhile either as an outcome or exposure in research. In a biologic sense, lipids do not function independently of one another and an analytic measure addressing their covariance is an asset. CFA leverages this characteristic of these measures to form a measure with different meaning from univariate indicators. Combining the observed correlations between the three common lipids alongside their common presentation in the literature and theoretical basis for dyslipidemia further justifies the use of CFA. Limitations include the possibility of a nonlinear association between these lipid indicators, which a CFA does not account for and may represent a mis-specified model.

Dyslipidemia as a multivariate construct can be an adjunct measure to univariate measures of lipids, which provides a means to assess the degree to which one measure increases as another measure either increase or decreases on a population level. Aside from the important caveat of measurement non-invariance, this work demonstrates the degree to which HDL-C, LDL-C and TG are correlated with one another on a population level. In turn this correlation when captured via CFA can provide meaningful interpretation with other factors in downstream analyses.

# References
